"""empty message

Revision ID: 1ba95173d7e2
Revises: 
Create Date: 2021-01-15 13:27:14.652149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba95173d7e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memetemplate',
    sa.Column('memeID', sa.Integer(), nullable=False),
    sa.Column('memeTemplateSavePathURI', sa.String(length=500), nullable=True),
    sa.Column('dialogue_template_name', sa.String(length=200), nullable=True),
    sa.Column('movieName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('memeID')
    )
    op.create_table('memetag',
    sa.Column('meme_tag_id', sa.Integer(), nullable=False),
    sa.Column('meme_tag', sa.String(length=50), nullable=True),
    sa.Column('memeID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['memeID'], ['memetemplate.memeID'], ),
    sa.PrimaryKeyConstraint('meme_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memetag')
    op.drop_table('memetemplate')
    # ### end Alembic commands ###
